### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Webx123** [itzzzme/m3u8proxy#1]
is their a way to attach headers? like referrer and origin or maybe user-agent but mostly referrer. ?

**Comment by itzzzme** [comment]
are you talking to implement it in the live deployed website or you want to customize the code?

**Comment by Webx123** [comment]
implemented would be easiest but if i could figure out how to change and deploy that would be cool to either way to be able to assign Referrer , orgin , user agent becaue some m3u8s require it to play

**Comment by itzzzme** [comment]
if you want to add extra header just add append headers on the m3u8 link by encoding it for example if you want to proxy a m3u8 file

e.g: https://example.com/master.m3u8 

and you want to append header

then append like this

`https://example.com/master.m3u8**%26headers%3D%7B%22referer%22%3A%22https%3A%2F%2Fexample.com%22%7D**`

don't add headers without encoding it otherwise it may cause not playing the video

`https://example.com/master.m3u8&headers={"referer":"https://example.com"}  //this is not a right method to get it work`

and if you want to implement on your own you can modify the html file and add an input tag to take the headers input and then encode the value in input tag using `encodeURIComponent(JSON.stringify(intputvalue))` 

You are good to go

**Comment by Webx123** [comment]
so it would be 
https://example.com/master.m3u8&headers={"referer":"https://example.com","origin":"https://example-origin.com","user-agent":"YourUserAgent"}
and usable would be https://example.com/master.m3u8&headers=%7B%22referer%22%3A%22https%3A%2F%2Fexample.com%22%2C%22origin%22%3A%22https%3A%2F%2Fexample-origin.com%22%2C%22user-agent%22%3A%22YourUserAgent%22%7D

**Comment by itzzzme** [comment]
usable would be 

`https://example.com/master.m3u8%26headers%3D%7B%22referer%22%3A%22https%3A%2F%2Fexample.com%22%2C%22origin%22%3A%22https%3A%2F%2Fexample-origin.com%22%2C%22user-agent%22%3A%22YourUserAgent%22%7D`

& and = has to be equally encoded as well

**Comment by Webx123** [comment]
Thats awesome works Flawlessly! thanks! i tried to make my own on vercel.app but it https://m3u8proxy-8kwt7m8z3-webx123s-projects.vercel.app/m3u8-proxy?url= dont work?

**Comment by itzzzme** [comment]
> Thats awesome works Flawlessly! thanks! i tried to make my own on vercel.app but it https://m3u8proxy-8kwt7m8z3-webx123s-projects.vercel.app/m3u8-proxy?url= dont work? 
> 
> i think its because its outputting http://0.0.0.0:8080/ts-proxy?url=https%3A%2F%2Fft-hetzner.3045x.com%2F9f41r40060icglir%2F82510038_82512038.js&headers=%7B%7D for some reason rather then 
> https://m3u8proxy-8kwt7m8z3-webx123s-projects.vercel.app/ts-proxy
> 
> 
Since it can't handle that IP for obvious reasons it will not be able to play

**Comment by Webx123** [comment]
> > Thats awesome works Flawlessly! thanks! i tried to make my own on vercel.app but it https://m3u8proxy-8kwt7m8z3-webx123s-projects.vercel.app/m3u8-proxy?url= dont work?
> > i think its because its outputting http://0.0.0.0:8080/ts-proxy?url=https%3A%2F%2Fft-hetzner.3045x.com%2F9f41r40060icglir%2F82510038_82512038.js&headers=%7B%7D for some reason rather then
> > https://m3u8proxy-8kwt7m8z3-webx123s-projects.vercel.app/ts-proxy
> 
> Since it can't handle that IP for obvious reasons it will not be able to play

yeah i know it cant handle local host 0.0.0 of course but how would i change it to use the Vercel url..

**Comment by itzzzme** [comment]
you have to add environment variable in vercel 

![Screenshot 2024-11-02 115433-mh](https://github.com/user-attachments/assets/df4732b2-a487-431c-9071-bfe68b3a51c5)

![image-mh](https://github.com/user-attachments/assets/7a9ab92c-136b-4b6d-b0a6-a31f265b42d7)

**Comment by Webx123** [comment]
Im new to this and totally confused what do i put in there? and where do i get the Client_key ect to add to it

**Comment by itzzzme** [comment]
> Im new to this and totally confused what do i put in there? and where do i get the Client_key ect to add to it 

Go to settings and then add environment variables. There is nothing called client_key which you have to add

**Comment by Webx123** [comment]
i added
HOST="localhost"
PORT="3030"
PUBLIC_URL="https://m3u8proxy-one.vercel.app"
(my url)
but still the output m3u shows 0.00.00? 
https://imgur.com/ojzJGoc.png 
![see](https://github.com/user-attachments/assets/8bcdbaa0-0cd8-4c1b-a8e0-8e7dbbc1181f)

**Comment by itzzzme** [comment]
after updating env variables you have to redeploy the code to vercel to update those changes. To do that you can do any changes to your code and vercel will automatically redeploy that

**Comment by Webx123** [comment]
yayy it worked! any idea what i could change to prevent it from the constant lag and what causes it to pause on load?

**Comment by itzzzme** [comment]
> yayy it worked! any idea what i could change to prevent it from the constant lag and what causes it to pause on load? 

It depends upon several factors like
- the m3u8 file
- your internet connection 
- player you are using for playing
- server you are using to host the proxy server

**Comment by Webx123** [comment]
Internet is 1000 Down , Jwplayer and all other videos are fine im using Vercel that may be the issue

**Comment by itzzzme** [comment]
> Internet is 1000 Down , Jwplayer and all other videos are fine im using Vercel that may be the issue 

Vercel gives a 100gb bandwidth limit per month. I was also using that which caused over usage of bandwidth and account pause. So that might be the reason if you overuse it. 
And I suggest using another third party player where you have control over it. E.g: artplayer or vidstack or plyr.io. I am not sure how jwplayer handles proxied segments of m3u8

**Comment by Webx123** [comment]
plyr.io! worked to fix the pause issue , any recommended servers to deploy on thats better?

**Comment by itzzzme** [comment]
you can try cloudflare worker script given in the repo to deploy it on cloudflare worker by following instruction in readme

**Comment by Webx123** [comment]
the old version is working amazing for me, i deployed a second copy of your updated script with the Domain Protection , But the m3u8s dont play even tho im embedding it to an alllowed orgin on my ENV allowed list any idea what would cause them not to play?

**Comment by Webx123** [comment]
im talking about vercel btw
