### ISSUE TITLE
Streaming links are not showing 

### ISSUE THREAD

**Issue by devachandru** [itzzzme/m3u8proxy#2]
![image](https://github.com/user-attachments/assets/39ff17b9-2959-4fb0-ad6e-06d6aa95222b)

**Comment by itzzzme** [comment]
> ![image](https://github.com/user-attachments/assets/39ff17b9-2959-4fb0-ad6e-06d6aa95222b)
> 

The streaming endpoint is not working correctly since the scraping source is not giving the correct response. It will be fixed very soon.

**Comment by itzzzme** [comment]
@devachandru Check out the API. It's fixed now
